name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🌟 Hey there, you just opened your first issue! That's worth celebrating! 🎉 We're as excited as a bunch of pandas at a bamboo festival. Let's tackle this together. And remember, there are no silly questions, just quirky answers (sometimes). 😄 Thanks for contributing!"
        pr-message: "🚀 Wow! Your first pull request! If this were a game, you'd have just earned experience points! 🎮 Gear up for an epic journey of code and collaboration. Our review team, sharper than a samurai sword on discount day, is ready to take a look. Thanks for powering the innovation spaceship! 🌌"

